// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.5
// source: hello.proto

package invoicer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HelloMsgService_Hello_FullMethodName = "/HelloMsgService/Hello"
)

// HelloMsgServiceClient is the client API for HelloMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloMsgServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloMsgServiceClient(cc grpc.ClientConnInterface) HelloMsgServiceClient {
	return &helloMsgServiceClient{cc}
}

func (c *helloMsgServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, HelloMsgService_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloMsgServiceServer is the server API for HelloMsgService service.
// All implementations must embed UnimplementedHelloMsgServiceServer
// for forward compatibility
type HelloMsgServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedHelloMsgServiceServer()
}

// UnimplementedHelloMsgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHelloMsgServiceServer struct {
}

func (UnimplementedHelloMsgServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHelloMsgServiceServer) mustEmbedUnimplementedHelloMsgServiceServer() {}

// UnsafeHelloMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloMsgServiceServer will
// result in compilation errors.
type UnsafeHelloMsgServiceServer interface {
	mustEmbedUnimplementedHelloMsgServiceServer()
}

func RegisterHelloMsgServiceServer(s grpc.ServiceRegistrar, srv HelloMsgServiceServer) {
	s.RegisterService(&HelloMsgService_ServiceDesc, srv)
}

func _HelloMsgService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloMsgServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloMsgService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloMsgServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloMsgService_ServiceDesc is the grpc.ServiceDesc for HelloMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HelloMsgService",
	HandlerType: (*HelloMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloMsgService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
